### ISSUE TITLE
eiis command error

### ISSUE THREAD

**Issue by wowsonsun** [njleonzhang/vscode-extension-mardown-image-paste#6]
When I installed ‘npm install -g electron-image-ipc-server’, type ‘eiis’ and the following error occurred.
![error](https://i.loli.net/2019/03/20/5c919b8ebacd9.png)

**Comment by wowsonsun** [comment]
I looked at the source code according to the prompt's error and found the prompt "spawn"
  Unknown" is in the source code

![source code](https://i.loli.net/2019/03/20/5c91a64a07437.jpg)

**Comment by njleonzhang** [comment]
sorry. it currently haven't tested on Windows, and just work for Mac os. I will try to support Windows later.

**Comment by wowsonsun** [comment]
Thank you, I am looking forward to supporting Windows. I hope this plugin can be marked for MAC only.= =

**Comment by njleonzhang** [comment]
@wowsonsun sorry for the convinience

**Comment by dreamer2q** [comment]
```bash
internal/child_process.js:405
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:548:9)
    at Object.<anonymous> (C:\Users\dreamer2q\scoop\persist\nodejs\bin\node_modules\electron-image-ipc-server\index.js:18:12)   
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

Same issue, frustrated!

**Comment by Amomum** [comment]
I also stumbled into this on my Windows 7.
Looks like the reason is that that `spawn` call for some reason tries to spawn a .js file directly and that is not possible on Windows; you have to run it like `node smth.js`.

Your package json _should_ have resolved that by 'bin' property - but for some reason it didn't.

So I tried to  change this spawn line:

``` js
electron = spawn(electronPath, [scriptPath, scriptPath], {
    env: spawn_env,
    stdio: ['pipe', 'pipe', 'pipe', 'ipc']
});
```
to this:

``` js
electron = spawn('node', [electronPath, scriptPath, scriptPath], {
    env: spawn_env,
    stdio: ['pipe', 'pipe', 'pipe', 'ipc']
});
```

And the error went away! However, extension still doesn't work :( and not giving any obvious errors anywhere. just quietly does nothing. Electron doesn't seem to be executed, my github API key is not used.
I'm not sure where to look next.
